
# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[2])
print(arr[-1])

1
3
9



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:6])

[3 4 5 6]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[[0,2]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[[0],[2]])

[1 3]
[3]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
arr = np.array([1,20,14,18,21,4,11,54,12])
print(arr[arr > 15])

[False  True False  True  True False False  True False]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)

[11 12 13 14 15]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

15
3.0
5
1



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [20]:
arr = np.array([11,34,1,2,56,111,4,5,6,30,34,55,78,90,23,45,67,89,12,34])
print(np.sort(arr))

[  1   2   4   5   6  11  12  23  30  34  34  34  45  55  56  67  78  89
  90 111]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))
print(np.vstack((arr1, arr2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
